<a href="https://colab.research.google.com/github/techshot25/CollegeMajors/blob/master/CollegeMajors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predicting college majors
By Ali J. Shannon


---

I will be a few machine learning methods from sklearn libraries to find the best predictor of the category of a major using unemployment rate and median income.  

In summary: the decision tree method offered the best predictor for college major .

The purpose of this project is to practice with machine learning algorithims and not analyze correlation between datasets. I will be doing that in a future project.

---

# College Majors

This folder contains the data and code behind the story [The Economic Guide To Picking A College Major](https://fivethirtyeight.com/features/the-economic-guide-to-picking-a-college-major/).

All data is from American Community Survey 2010-2012 Public Use Microdata Series.

Download data here: http://www.census.gov/programs-surveys/acs/data/pums.html

Documentation here: http://www.census.gov/programs-surveys/acs/technical-documentation/pums.html

The three headers from `all-ages.csv` to be considered here are shown below:

Header | Description
---|---------
`Major_category` | Category of major from Carnevale et al
`Unemployment_rate` | Unemployed / (Unemployed + Employed)
`Median` | Median earnings of full-time, year-round workers

In [7]:
import pandas as pd
import numpy as np

# read the data file
df = pd.read_csv('all-ages.csv')

# print the three columns that will be used
df[['Major_category','Unemployment_rate', 'Median']]

                          Major_category  Unemployment_rate  Median
0        Agriculture & Natural Resources           0.026147   50000
1        Agriculture & Natural Resources           0.028636   54000
2        Agriculture & Natural Resources           0.030248   63000
3        Agriculture & Natural Resources           0.042679   46000
4        Agriculture & Natural Resources           0.049188   62000
5        Agriculture & Natural Resources           0.031791   50000
6        Agriculture & Natural Resources           0.050867   63000
7        Agriculture & Natural Resources           0.039230   52000
8                 Biology & Life Science           0.051290   52000
9        Agriculture & Natural Resources           0.042563   58000
10       Agriculture & Natural Resources           0.054341   52000
11                           Engineering           0.085991   63000
12             Humanities & Liberal Arts           0.067939   46000
13           Communications & Journalism           0.064360   50000
14           Communications & Journalism           0.061917   50000
15           Communications & Journalism           0.083005   48000
16           Communications & Journalism           0.067216   50000
17               Computers & Mathematics           0.085009   50000
18               Computers & Mathematics           0.051891   65000
19               Computers & Mathematics           0.090264   60000
20               Computers & Mathematics           0.049519   78000
21               Computers & Mathematics           0.052841   68000
22               Computers & Mathematics           0.075046   55000
23               Computers & Mathematics           0.058694   55000
24   Industrial Arts & Consumer Services           0.054941   40000
25                             Education           0.043904   43000
26                             Education           0.000000   58000
27                             Education           0.101746   41000
28                             Education           0.038359   40000
29                             Education           0.032983   43000
..                                   ...                ...     ...
143                                 Arts           0.085619   47000
144            Humanities & Liberal Arts           0.063913   44500
145                                 Arts           0.083714   37600
146                                 Arts           0.156147   45000
147                               Health           0.054701   50000
148                               Health           0.046467   42000
149                               Health           0.057004   50000
150                               Health           0.031357   55000
151                               Health           0.036210   60000
152                               Health           0.070010   50000
153                               Health           0.026797   62000
154                               Health           0.034358  106000
155                               Health           0.026292   61000
156                               Health           0.066528   47000
157                               Health           0.053573   45000
158                             Business           0.051378   60000
159                             Business           0.053415   65000
160                             Business           0.056064   72000
161                             Business           0.058865   58000
162                             Business           0.043268   65000
163                             Business           0.061749   65000
164                             Business           0.055033   56000
165                             Business           0.048473   65000
166                             Business           0.060748   54000
167                             Business           0.071354   54000
168                             Business           0.051447   49000
169                             Business           0.043977   72000
170                             Business           0.052679   53000
171            Humanities & Liberal Arts           0.065851   50000
172            Humanities & Liberal Arts           0.073500   50000

[173 rows x 3 columns]

Now we need to define features and categories **X** will be our matrix of features, **y** will repsent our categories. The features will be the `Unemployment_rate` and `Median`. The categories will be `Major_category`.

In [0]:
y = df[['Major_category']].values.tolist()
X = df[['Unemployment_rate', 'Median']].values.tolist()

Using DecisionTreeClassifier from sklearn.

Splitting the data into training_data and test_data.

Training data will be used to train our dataset. Test_data will be used to find the accuracy of our prediction method

In [21]:
from sklearn import tree

# This just takes out every fifth element to use for testing
test_idx = [x for x in range(len(y)) if x%5 == 0]

train_target = np.delete(y, test_idx)
train_data = np.delete(X, test_idx, axis = 0)

test_target = [y[i] for i in test_idx]
test_data = [X[i] for i in test_idx]

decisionTree = tree.DecisionTreeClassifier()
decisionTree = clf.fit(train_data, train_target)

from sklearn.metrics import accuracy_score

predictions1 = decisionTree.predict(test_data)
print(accuracy_score(test_target, predictions1))

0.22857142857142856

I have built a simple decision tree classifier and a basic KNN in the practice repository I have listed here: 
https://github.com/techshot25/MachineLearningPractice

To save myself the effort of building another from scratch. I have employed sklearn's methods

In [22]:
from sklearn.neighbors import KNeighborsClassifier

kNN = KNeighborsClassifier()
kNN = kNN.fit(train_data, train_target)

predictions2 = kNN.predict(test_data)
print(accuracy_score(test_target, predictions2))

0.2571428571428571

In [23]:
from sklearn import svm

SupportVectorMachine = svm.SVC(gamma='scale')
SupportVectorMachine.fit(train_data, train_target)  

predictions3 = SupportVectorMachine.predict(test_data)
print(accuracy_score(test_target, predictions3))

0.2571428571428571